/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    'rbac_message': MotiaStream<{ message: string; from: 'user' | 'assistant'; status: 'created' | 'pending' | 'completed' }>
    'message': MotiaStream<{ message: string; from: 'user' | 'assistant'; status: 'created' | 'pending' | 'completed' }>
    'rbac_message_python': MotiaStream<{ message: string; from: 'user' | 'assistant'; status: 'created' | 'pending' | 'completed' }>
    'message_python': MotiaStream<{ message: string }>
  }

  interface Handlers {
    'TestStateCheck': EventHandler<{ key: string; expected?: unknown }, never>
    'TestStateApiTrigger': ApiRouteHandler<{}, unknown, { topic: 'test-state-python'; data: unknown }>
    'Download PDF': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Buffer>, never>
    'Download HTML': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, Buffer>, never>
    'RbacStreamApi': ApiRouteHandler<{ message: string; streamName: 'rbac_message' | 'rbac_message_python' }, ApiResponse<200, { message: string; from: 'user' | 'assistant'; status: 'created' | 'pending' | 'completed' }>, { topic: 'rbac-prompt'; data: { message: string; assistantMessageId: string; threadId: string; streamName: 'rbac_message' | 'rbac_message_python' } }>
    'MockRbacStream': EventHandler<{ message: string; assistantMessageId: string; threadId: string; streamName: 'rbac_message' | 'rbac_message_python' }, never>
    'stepA': EventHandler<{}, { topic: 'pms.stepA.done'; data: { msg: string; timestamp: number } }>
    'Parallel Merge': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'pms.start'; data: {} }>
    'join-step': EventHandler<{ msg: string; timestamp: number }, { topic: 'pms.join.complete'; data: { stepA: { msg: string; timestamp: number }; stepB: { msg: string; timestamp: number }; stepC: { msg: string; timestamp: number }; mergedAt: string } }>
    'JoinComplete': EventHandler<{ stepA: { msg: string; timestamp: number }; stepB: { msg: string; timestamp: number }; stepC: { msg: string; timestamp: number }; mergedAt: string }, never>
    'CallOpenAi': EventHandler<{ message: string; assistantMessageId: string; threadId: string }, never>
    'OpenAiApi': ApiRouteHandler<{ message: string }, ApiResponse<200, { message: string; from: 'user' | 'assistant'; status: 'created' | 'pending' | 'completed' }>, { topic: 'openai-prompt'; data: { message: string; assistantMessageId: string; threadId: string } }>
    'SqsNotification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ProcessFoodOrder': EventHandler<{ email: string; quantity: number; petId: string }, { topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'PeriodicJobHandled': EventHandler<{ message: string }, { topic: 'tested'; data: never }>
    'HandlePeriodicJob': CronHandler<{ topic: 'periodic-job-handled'; data: { message: string } }>
    'StaleJobMonitor': CronHandler<never>
    'StateAuditJob': CronHandler<{ topic: 'notification'; data: { templateId: string; email: string; templateData: Record<string, unknown> } }>
    'Notification': EventHandler<{ templateId: string; email: string; templateData: Record<string, unknown> }, never>
    'ApiTrigger': ApiRouteHandler<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'ArrayStep': ApiRouteHandler<Array<{ pet: { name: string; photoUrl: string }; foodOrder?: { quantity: number } }>, ApiResponse<200, Array<{ id: string; name: string; photoUrl: string }>>, { topic: 'process-food-order'; data: { email: string; quantity: number; petId: string } }>
    'StaffDashboardAPI': ApiRouteHandler<{}, unknown, never>
    'HealthCheck': ApiRouteHandler<{}, unknown, never>
    'BrainService': ApiRouteHandler<{ businessData: Record<string, unknown>; directory: string; useAI?: boolean }, unknown, never>
    'Test State With Python': EventHandler<unknown, { topic: 'test-state-check'; data: { key: string; expected?: unknown } }>
    'Test Event': EventHandler<never, { topic: 'tested'; data: never }>
    'Tested Event': EventHandler<never, never>
    'Test API Endpoint': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'test'; data: never }>
    'stepC': EventHandler<never, { topic: 'pms.stepC.done'; data: { msg: string; timestamp: number } }>
    'stepB': EventHandler<never, { topic: 'pms.stepB.done'; data: { msg: string; timestamp: number } }>
    'CallOpenAiPython': EventHandler<{ message: string; assistantMessageId: string; threadId: string }, never>
    'OpenAiApiPython': ApiRouteHandler<{ message: string; threadId?: string }, ApiResponse<200, { threadId: string }>, { topic: 'openai-prompt-python'; data: { message: string; assistantMessageId: string; threadId: string } }>
    'PythonStateAuditJob': CronHandler<{ topic: 'python-notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'PythonProcessFoodOrder': EventHandler<{ email: string; quantity: unknown; pet_id: string }, { topic: 'python-notification'; data: { template_id: string; email: string; template_data: Record<string, unknown> } }>
    'PythonNotification': EventHandler<{ template_id: string; email: string; template_data: Record<string, unknown> }, never>
    'PythonApiTrigger': ApiRouteHandler<{ pet: unknown; foodOrder?: unknown | unknown }, ApiResponse<200, { id: string; name: string; photoUrl: string }>, { topic: 'python-process-food-order'; data: { email: string; quantity: unknown; pet_id: string } }>
  }
    interface StreamAuthContext unknown
}